name: Cosmo Test Project

on:
  push:
    branches: [main]
  # Caso precise rodar a action manualmente
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn ci

      - name: Build Project
        run: |
          cd page
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.VITE_GITHUB_ACCESS_TOKEN }}
          publish_dir: ./dist
          branch: gh-pages # The branch the action should deploy to.
          folder: page/build # The folder the action should deploy.
